### ISSUE TITLE
Check máy client

### ISSUE THREAD

**Issue by ha-dang-khoa** [wewo-ecommerce/wewo#37]
Check máy client có đã root không? 
Nếu có root thì vào đăng xuất

**Comment by dongduc3** [comment]
> Check máy client có đã root không? Nếu có root thì vào đăng

**Comment by ha-dang-khoa** [comment]
Bằng chứng CPPT task này:
Phần code @dongduc3 : 800 CPPT

Có bổ sung thì ý kiến em nhé./.
